#FROM tensorflow/tensorflow:latest-gpu-py3
FROM tensorflow/tensorflow:1.12.0-rc0-py3
MAINTAINER Paul Felt (paul.lewis.felt@gmail.com)

COPY ./requirements.txt /

# pip 
RUN pip3 install -r /requirements.txt

